# Generated by Django 4.2.2 on 2023-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='id',
        ),
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
