# Generated by Django 4.2.2 on 2023-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_links_id_alter_links_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='img',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='links',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
